apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.applicationName }}
spec:
  hosts:
  - "*"
  gateways:
  - {{ .Values.applicationName }}
  http:
  - match:
    - uri:
        prefix: /frota
    route:
    - destination:
        host: {{ .Values.applicationName }}
        port:
          number: 80