apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.applicationName }}
spec:
  hosts:
  - "*"
  gateways:
  - {{ .Values.applicationName }}
  http:
  - match:
    - headers:
        x-app-version:
          exact: canary
    route:
    - destination:
        host: {{ .Values.applicationName }}
        port:
          number: 80
        subset: canary
  - match:
    - uri:
        prefix: {{ .Values.gateway.prefix }}
    route:
    - destination:
        host: {{ .Values.applicationName }}
        port:
          number: 80
        subset: {{ .Values.applicationVersion }}
    #   weight: {{ sub  100 .Values.gateway.canaryPorcentege }} 
    # - destination:
    #     host: {{ .Values.applicationName }}
    #     port:
    #       number: 80
    #     subset: canary
    #   weight: {{ .Values.gateway.canaryPorcentege }}