applicationName: frota-backend
applicationVersion: v1
namespace: frotas

deployment:
  image:
    repository: docker.io
    name: samuelfantini/frota-backend
    tag: latest
    imagePullSecret: hubsecret
    pullPolicy: IfNotPresent
  replicaCount: 1
  containerPort: 8080
  protcol: http

healthCheckPath:
  readinessProbe:
    path: /health/ready
    port: 8080
    initialDelaySeconds: 15
    periodSeconds: 30
    timeoutSeconds: 1
    failureThreshold: 3
  livenessProbe:
    path: /health/live
    port: 8080
    initialDelaySeconds: 100
    periodSeconds: 15
    timeoutSeconds: 1
    failureThreshold: 3

resources:
  requests:
    cpu: 10m
    memory: 64Mi
  limits:
    cpu: 25m
    memory: 128Mi

hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  metricName: memory
  averageUtilization: 70

service:
  externalPort: 80
  protcol: TCP