applicationName: frota-backend
applicationVersion: canary
namespace: frotas

deployment:
  name: frota-backend-canary
  image:
    repository: docker.io
    name: samuelfantini/frota-backend
    tag: canary
    imagePullSecret: hubsecret
    pullPolicy: IfNotPresent
  replicaCount: 1
  containerPort: 8080
  protcol: http

healthCheckPath:
  readinessProbe:
    path: /api/frotas/health/ready
    port: 8080
    initialDelaySeconds: 15
    periodSeconds: 30
    timeoutSeconds: 1
    failureThreshold: 3
  livenessProbe:
    path: /api/frotas/health/live
    port: 8080
    initialDelaySeconds: 100
    periodSeconds: 15
    timeoutSeconds: 1
    failureThreshold: 3

resources:
  requests:
    cpu: 10m
    memory: 64Mi
  limits:
    cpu: 25m
    memory: 128Mi
